name: Deploy

on:
  push:
    branches: [ main ]
  release:
    types: [released]
  workflow_dispatch:

jobs:
  linux_build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install firebase
        run: npm install -g firebase-tools
      - name: Initialize
        run: |
          firebase init --token { FIREBASE_TOKEN }
      - name: deploy
        run: |
          firebase deploy --only hosting:etcetra7n
          
